---
title: "Predicting Survival from GO terms"
author: "Will Townes"
date: "6/29/2018"
output: html_document
---

```{r}
#library(doParallel)
#registerDoParallel(makeCluster(detectCores()-1)) #3 cores on mac
library(dplyr)
source("./carets.R") #loads caret, ROCR, ggplot2
spp<-c("yeast","worm")
sp<-spp[2]
fts<-"go"
```

Data Loading

```{r}
dat<-readRDS(paste0("./data/auto/",sp,".rds"))
y<-rep("anti",length(dat$y))
y[dat$y==1]<-"pro"
y<-factor(y)
ytrn<-y[dat$train_idx]
ytst<-y[-dat$train_idx]
X<-dat[[fts]]
mode(X)<-"numeric"
Xtrn<-X[dat$train_idx,]
Xtst<-X[-dat$train_idx,]
```

all algorithms

```{r}
mods<-c("kknn","xgbTree","svmRadialSigma","glmnet","nb")
f<-function(m){
  print(m)
  fitcaret(Xtrn,ytrn,m)
}
system.time(res<-sapply(mods,f,simplify=FALSE))
#system.time(res<-parallel::mclapply(mods,f,mc.cores=3))
#names(res)<-mods
#res2<-lapply(res,caret_roc,Xtst,ytst,ytrn)
res2<-list()
for(j in mods){
  print(j)
  res2[[j]]<-caret_roc(res[[j]],Xtst,ytst,ytrn)
  res2[[j]]$alg<-j
}
pd<-do.call(rbind,res2)
ggplot(subset(pd,fold=="test"),aes(x=fpr,y=tpr,col=alg))+geom_line()+theme_bw()
pd %>% subset(fold=="test") %>% group_by(alg) %>% summarize(auc=roc2auc(fpr,tpr)) %>% arrange(desc(auc))
```

knn classifier

```{r}
#knn via caret
system.time(fit<-train(Xtrn, ytrn, preProcess=NULL, metric="Kappa", trControl=trainControl("repeatedcv",5,repeats=2),  method="kknn"))
#tuneGrid=expand.grid(kmax=c(5,10,15),distance=c(1,2),kernel="optimal")
print(fit)
perf<-caret_roc(fit,Xtst,ytst,ytrn)
ggplot(perf,aes(x=fpr,y=tpr,col=fold))+geom_line()+theme_bw()+geom_abline(slope=1,intercept=0,alpha=.5)
roc2auc(perf$fpr[perf$fold=="test"],perf$tpr[perf$fold=="test"])
```

xgboost

```{r}
system.time(fit<-train(Xtrn, ytrn, preProcess=NULL, metric="Kappa", trControl=trainControl("repeatedcv",5,repeats=2),  method="xgbTree"))
print(fit)
perf<-caret_roc(fit,Xtst,ytst,ytrn)
ggplot(perf,aes(x=fpr,y=tpr,col=fold))+geom_line()+theme_bw()+geom_abline(slope=1,intercept=0,alpha=.5)
roc2auc(perf$fpr[perf$fold=="test"],perf$tpr[perf$fold=="test"])
```

svm with caret
```{r}
system.time(fit<-train(Xtrn, ytrn, preProcess=NULL, metric="Kappa", trControl=trainControl("repeatedcv",5,repeats=2),  method="svmRadialSigma", prob.model=TRUE))
print(fit)
perf<-caret_roc(fit,Xtst,ytst,ytrn)
ggplot(perf,aes(x=fpr,y=tpr,col=fold))+geom_line()+theme_bw()+geom_abline(slope=1,intercept=0,alpha=.5)
roc2auc(perf$fpr[perf$fold=="test"],perf$tpr[perf$fold=="test"])
```

GLMnet prediction

```{r}
system.time(fit<-train(Xtrn, ytrn, preProcess=NULL, metric="Kappa", trControl=trainControl("repeatedcv",5,repeats=2),  method="glmnet", family="binomial"))
print(fit)
perf<-caret_roc(fit,Xtst,ytst,ytrn)
ggplot(perf,aes(x=fpr,y=tpr,col=fold))+geom_line()+theme_bw()+geom_abline(slope=1,intercept=0,alpha=.5)
roc2auc(perf$fpr[perf$fold=="test"],perf$tpr[perf$fold=="test"])
```

naive bayes- it needs to throw out sparse predictors with "nzv" preprocessing

```{r}
tg=expand.grid(fL=c(0,0.5,1.0),usekernel=TRUE,adjust=c(0.5,1.0))
system.time(fit<-train(Xtrn, ytrn, preProcess="nzv", metric="Kappa", trControl=trainControl("repeatedcv",5,repeats=2),  method="nb", tuneGrid=tg, prior=table(ytrn)/length(ytrn)))
print(fit)
perf<-caret_roc(fit,Xtst,ytst,ytrn)
ggplot(perf,aes(x=fpr,y=tpr,col=fold))+geom_line()+theme_bw()+geom_abline(slope=1,intercept=0,alpha=.5)
roc2auc(perf$fpr[perf$fold=="test"],perf$tpr[perf$fold=="test"])
```

