#This script should be run after 01_data_loading.Rmd
fp<-file.path

make_predictors<-function(features,dat){
  #features a string like "go" or "go_archs4"
  #dat a list generated by load_data function
  #output: design matrix X suitable for regression modeling
  fts<-unlist(strsplit(features,"_"))
  do.call(cbind,dat[fts])
}

species<-c("worm","yeast")

if(!dir.exists("./results/auto")){
  dir.create("./results/auto",recursive=TRUE)
}
predictors<-c("go","archs4","other1","go_archs4","go_other1")
#yeast other1 is deleteome measured genes
#worm other1 is merged UMIs of worm cell atlas
algs<-c("svmradial","knn","glmnet")#,"gbm")
for(sp in species){
  pth<-fp("./results/auto",sp)
  if(!dir.exists(fp(pth,"roc"))){
    dir.create(fp(pth,"roc"))
  }
  rname<-paste0(pth,"performance.csv")
  if(!file.exists(rname)){
    d<-expand.grid(outcome="genage_pro_anti", predictors=predictors, algs=algs, auc=NA)
    write.csv(d,file=rname)
  }
  d<-read.csv(rname)
  dat<-readRDS(paste0("./data/auto/",sp,".rds"))
  for(i in 1:nrow(d)){
    if(!is.na(d[i,"auc"])){ next }
    X<-make_predictors(d[i,"predictors"],dat)
    y<-dat$y
    
  }
}

