#>>time Rscript 07_setup_autorun.R
#This script should be run after 01_data_loading.Rmd
#library(parallel)
source("./carets.R")

fp<-file.path

mkdir_p<-function(d){
  if(!dir.exists(d)){ dir.create(d,recursive=TRUE) }
}

make_predictors<-function(features,dat){
  #features a string like "go" or "go_archs4"
  #dat a list generated by load_data function from 01_data_loading.Rmd
  #output: design matrix X suitable for regression modeling
  fts<-unlist(strsplit(features,"_"))
  do.call(cbind,dat[fts])
}

caret_all<-function(Xtrn,ytrn){
  algs<-c("kknn","xgbTree","svmRadialSigma","glmnet","nb")
  f<-function(a,Xtrn,ytrn){fitcaret(Xtrn,ytrn,a)}
  fits<-sapply(algs,f,Xtrn,ytrn,simplify=FALSE)
}

dat2roc<-function(features,dat,basedir,usecache=TRUE,verbose=TRUE){
  #features is a string saying what predictors to use (eg go_gxp)
  #dat is the list of all data
  #caches the list of fitted models (all algs) under <basedir>/<features>/carets.rds
  #writes the tpr and fpr (ROC) to <basedir>/<features>/roc.txt
  #basedir is usually something like "./results/auto/yeast"
  pth<-fp(basedir,features) #eg "./results/auto/yeast/go_gxp"
  if(verbose){ print(pth) }
  mkdir_p(pth)
  cachepath<-fp(pth,"carets.rds")
  y<-rep("anti",length(dat$y))
  y[dat$y==1]<-"pro"
  y<-factor(y)
  ytrn<-y[dat$train_idx]
  ytst<-y[-dat$train_idx]
  X<-make_predictors(features,dat)
  mode(X)<-"numeric"
  Xtrn<-X[dat$train_idx,]
  Xtst<-X[-dat$train_idx,]
  if(usecache && file.exists(cachepath)){
    #if(verbose){ print("reusing cached caret fits") }
    fits<-readRDS(cachepath)
  } else {
    #if(verbose){ print("fitting caret models") }
    fits<-caret_all(Xtrn,ytrn)
    saveRDS(fits,file=cachepath)
  }
  rocfunc<-function(a){
    d<-caret_roc(fits[[a]],Xtst,ytst,ytrn)
    d$alg<-a
    d
  }
  res<-do.call(rbind,lapply(names(fits),rocfunc))
  write.table(res,file=fp(pth,"roc.txt"),quote=FALSE,row.names=FALSE)
}

master<-function(sp,ft){
  #sp="worm" or "yeast"
  #ft= "go", "gxp", "go_gxp" etc
  #runs all algorithms for the species/features combo and saves to file
  sp<-as.character(sp); ft<-as.character(ft)
  dat<-readRDS(fp("./data/auto",paste0(sp,".rds")))
  dat2roc(ft,dat,fp("./results/auto",sp),usecache=TRUE,verbose=TRUE)
}

species<-c("worm","yeast")
for(sp in species){ mkdir_p(fp("./results/auto",sp)) }
fts<-c("go","archs4","gxp","go_archs4","go_gxp")
#yeast gxp is deleteome measured genes
#worm gxp is merged UMIs of worm cell atlas
atlas<-expand.grid(fts=fts,species=species)
parallel::mcmapply(master,atlas$species,atlas$fts,mc.cores=4)
#mapply(master,atlas$species,atlas$fts)
