---
title: "McCormick 2015"
author: "Will Townes"
date: "9/14/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

# Exploratory Data Analysis of McCormick 2015

This is genetic perturbation and replicative lifespan data for almost all genes in yeast.

```{r}
merge_lifespans<-function(x){
  #x is a vector like c("4,3,5","2,3,1","9")
  #returns a single string concatenating all values together
  paste0(x,collapse=",")
}
str2vec<-function(x){as.numeric(unlist(strsplit(x,",",fixed=TRUE)))}
str2mean<-function(y){
  vapply(y,function(t){mean(str2vec(t))},FUN.VALUE=1.0)
}
str2count<-function(y){
  vapply(y,function(t){length(str2vec(t))},FUN.VALUE=1)
}

d0<-read.csv("data/mccormick2015.csv",stringsAsFactors=FALSE)
#remove bad genotypes with missing data
#need to pool across experiments
d<-d0[,c("set_genotype","set_lifespans","ref_lifespans")]
d<-d %>% group_by(set_genotype) %>% summarise(set_lifespans=merge_lifespans(set_lifespans),ref_lifespans=merge_lifespans(ref_lifespans))
d<-d %>% transform(set_lifespan_count=str2count(set_lifespans),set_lifespan_mean=str2mean(set_lifespans),ref_lifespan_mean=str2mean(ref_lifespans))
d<-d %>% transform(percent_change=(set_lifespan_mean-ref_lifespan_mean)*100/ref_lifespan_mean)
bad<-d %>% filter(percent_change>30 & set_lifespan_count<=5)
bad<-bad$set_genotype
d<-d0[!(d0$set_genotype %in% bad),]

sort(table(d$ref_genotype),decreasing=TRUE)
#restrict data to only the reference genotypes BY4742 and BY4741 (this is almost everything)
d<-d[d$ref_genotype %in% c("BY4742","BY4741"),]
#restrict to experiments with same ref and set background
d<-d[d$ref_background==d$set_background,]
#misc data cleanup, remove extra cols
#all experiments had set media YPD and temp 30C
extra_cols<-c("ref_locus_tag","set_locus_tag","pooled_by","ref_temperature","set_temperature","set_media","ref_media")
d[,extra_cols]<-NULL

#how many single gene vs multi gene deletions?
sg<-strsplit(as.character(d$set_genotype)," ",fixed=TRUE)
mcp<-unique(unlist(sg))
mcp<-toupper(mcp) #list of unique gene symbols perturbed
#number of genes perturbed in each experiment
ng<-sapply(sg,length)
table(ng)
#restrict to only single-gene deletions
d1<-d[ng==1,]
#mating types
table(d1$ref_mating_type)

cnames<-c("name","background","mating_type","genotype","lifespans")
d1s<-d1[,c("id","experiments",paste("set",cnames,sep="_"))]
colnames(d1s)[3:ncol(d1s)]<-cnames
d1s$is_ref<-FALSE
d1r<-d1[,c("id","experiments",paste("ref",cnames,sep="_"))]
colnames(d1r)[3:ncol(d1r)]<-cnames
d1r$is_ref<-TRUE
d1<-rbind(d1s,d1r)
d1$bind_id<-seq.int(nrow(d1))
lifespans<-strsplit(d1$lifespans,",",fixed=TRUE)
lifespans<-lapply(lifespans,as.numeric)
n<-sapply(lifespans,length)
d1a<-data.frame(lifespan=unlist(lifespans),bind_id=rep(d1$bind_id,n))
d1$lifespans<-NULL
for(j in c("id","experiments","name","background","mating_type","genotype")){
  d1[,j]<-factor(d1[,j])
}
#one row per data point instead of per experiment
d1<-merge(d1,d1a,by="bind_id")
```

sanity check, replicate figure 3a from paper with survival curves

```{r}
library(survival)
library(survminer)
los1_ids<-unique(d1$id[d1$genotype=="los1"])
q<-d1[d1$id %in% los1_ids,]
q$geno<-ifelse(q$genotype=="los1","los1","WT")
fit<-survfit(Surv(lifespan)~geno,data=q)
ggsurvplot(fit,data=q)
```

```{r}
#compare to deleteome stuff
source("load_deleteome.R")
"VMA2" %in% gdata$geneSymbol
table(mcp %in% perts)
table(mcp %in% gdata$geneSymbol)
head(mcp[!(mcp %in% gdata$geneSymbol)])
table(perts %in% mcp)
table(perts %in% mcp,perts %in% gdata$geneSymbol)
```