---
title: "Simulations"
author: "Will Townes"
date: "3/8/2018"
output: html_document
---

```{r}
#library(MASS)
library(rjags)
library(rstan)
rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores()-1)
```

```{r}
G<-50 #number of genes
#N<-2*G #number of perturbations
K<-5 #number of gene clusters (pathways), avg of G/K genes per pathway
L<-4 #latent dimensional space
Ls<-2 #survival latent dimensions
b<-c(-5,5,rep(0,L-Ls)) #coefficients for survival outcome
x<-rep(1:G,2) #index of which gene is perturbed in each experiment
#complete data- we perturb every gene twice
#first perturbation is to get survival
#second perturbation is to get gene expression
is_survival<-rep(c(TRUE,FALSE),each=G)
N<-length(x)
sigma_phi<-1.5
sigma_a<-.2
sigma_v<-1
sigma_psi<-sigma_phi
sigma_u<-0.1
sigma_w<-1
mu_w<-rnorm(G,sd=.1)
mu_y<-100
sigma_y<-2
bulk_ncells<-1e4
psi<-matrix(rnorm(K*L,sd=sigma_psi),nrow=L,ncol=K)
#psi=loadings of latent dimensions onto expression for a gene cluster
phi<-matrix(rnorm(K*L,sd=sigma_phi),nrow=L,ncol=K)
#cols=gene clusters, rows=latent dimensions
#first five cols=clusters related to survival
#first five rows= dimensions related to survival
phi[1:Ls,]<-phi[1:Ls,]/2 #less variability in first five dims
phi[1:Ls,1:Ls]<-phi[1:Ls,1:Ls]+5*diag(Ls)
image(phi)
cg<-sort(rep_len(1:K,G)) #cluster membership for each gene
a<-matrix(rnorm(G*L,sd=sigma_a),nrow=L,ncol=G)
v<-matrix(rnorm(G*L,sd=sigma_v),nrow=L,ncol=G)
for(g in 1:G){
  a[,g]<-a[,g]+phi[,cg[g]]
  v[,g]<-v[,g]+psi[,cg[g]]
}
u_surv<-matrix(rnorm(G*L,sd=sigma_u),nrow=L,ncol=G)
u_gxp<-matrix(rnorm(G*L,sd=sigma_u/sqrt(bulk_ncells)),nrow=L,ncol=G)
u<-cbind(u_surv,u_gxp)
for(n in 1:N){
  u[,n]<-u[,n]+a[,x[n]]
}
u_surv<-u[,1:G]
u_gxp<-u[,G+1:G]
w<-matrix(rnorm(G*ncol(u_gxp),sd=sigma_w),nrow=G)
w<-w+mu_w+crossprod(v,u_gxp)
#rows=measured genes, cols=perturbed genes
y<-crossprod(u_surv,b)+mu_y+rnorm(ncol(u_surv),sd=sigma_y)
```

hand code the phi_k coefficient vector prototypes. 2 of 4 are survival related (have large values in first 2 dimensions)

Confirm that first 2 gene clusters have significant effect on survival

```{r}
#get gene cluster info for each perturbation
pert_clust<-cg[x[is_survival]]
boxplot(y~factor(pert_clust),xlab="gene cluster/pathway",ylab="simulated lifespan")
#first two clusters: negative effect on survival
#clusters 3,4,5: positive efffect on survival
```

Confirm whether we can recover clusters by gene expression data

```{r}
#viz clustering by perturbation pattern
factors<-as.data.frame(prcomp(t(w))$x[,1:2])
factors$cl_true<-cg
plot(factors[,1],factors[,2],col=factors$cl_true)
#viz clustering by expression pattern across perts
factors<-as.data.frame(prcomp(w)$x[,1:2])
factors$cl_true<-cg
plot(factors[,1],factors[,2],col=factors$cl_true)
#kmeans on genes across perturbation
cl<-kmeans(w,K)$cluster
cl_compare<-table(cl,cg)
heatmap(cl_compare)
mclust::adjustedRandIndex(cl,cg)
#the clusterings are roughly concordant
```

Create subsets of data for training and test

```{r}
perts_surv<-sample.int(G,size=floor(G/2))
survtest<-setdiff(1:G,perts_surv)
perts_expr<-sample.int(G,size=floor(G/3))
exprtest<-setdiff(1:G,perts_expr)
y_train<-y[perts_surv]
w_train<-w[,perts_expr]
xx<-x[!is_survival]
xx_train<-xx[perts_expr]
xs<-x[is_survival]
xs_train<-xs[perts_surv]

#test data
y_test<-y[survtest]
w_test<-w[,exprtest]
xs_test<-xs[survtest]
xx_test<-xx[exprtest]
```

Try Stan model

```{r}
stmod<-stan_model("integrated_model.stan")
Xs_train<-model.matrix(~factor(xs_train,levels=1:G)-1)
Xx_train<-model.matrix(~factor(xx_train,levels=1:G)-1)
sdat<-list(xx=xx_train, xs=xs_train, Nx=length(xx_train), Ns=length(xs_train), ncell_s=rep_len(1,length(xs_train)), ncell_x=bulk_ncells, L=4, K=5, G=nrow(w_train), W=w_train, y=y_train, dir_wts=rep(1,K), Ls=2)
res<-sampling(stmod, sdat, chains=3)
```

Run integrated JAGS model

```{r}
#data for JAGS
jdat<-list(xx=xx_train, xs=xs_train, Nx=length(xx_train), Ns=length(xs_train), ncell_s=rep_len(1,length(xs_train)), ncell_x=bulk_ncells, L=4, K=5, G=nrow(w_train), W=w_train, y=y_train, dir_wts=rep(1,K))
system.time(jmod<-jags.model("integrated_model.bugs", data=jdat, n.chains=3, quiet=FALSE)) #this took almost 10 hours!
update(jmod, 10000)#, progress.bar="none")
jpars<-c("A","V","b","mu_w","tau_w","Psi","Phi","tau_v","tau_a","tau_y","theta","delta","mu_y")
system.time(samps0<-coda.samples(jmod, variable.names=jpars, n.iter=50000)) 
#list of length n.chains
#convert to data frame
samps<-do.call("rbind",samps0)
#colMeans(samps[,grepl("b",colnames(samps))])
hist(samps[,"mu_y"])
test_rmse<-function(s,samps,xs_test,y_test,jdat){
  #s indexes a sample from Gibbs
  A<-samps[s,grepl("A",colnames(samps))]
  A<-matrix(A,nrow=jdat$G)
  U<-A[xs_test,]
  b<-samps[s,grepl("b",colnames(samps))]
  mu_y<-samps[s,grepl("mu_y",colnames(samps))]
  ypred<-U%*%b+mu_y
  sqrt(mean((y_test-ypred)^2))
}
err<-lapply(samps0,function(samps){sapply(1:nrow(samps),test_rmse,samps,xs_test,y_test,jdat)})
err<-data.frame(err)
matplot(err,type="l")
#naive error
sqrt(mean((y_test-mean(y_train))^2))
```
